### ISSUE TITLE
BVM nodes

### ISSUE THREAD

**Issue by zeffii** [Sverchok/SverchokRedux#13]
dunno what this is and how it might impact us.

https://developer.blender.org/feed/?after=6220635745416549599

https://www.youtube.com/watch?v=oHsGfM7m2DA

**Comment by ly29** [comment]
We will have to see, I will continue playing until it becomes clear, that is the future of course.

**Comment by zeffii** [comment]
yeah. exciting but quite vague. neat as an custom modifier tho :)

**Comment by nortikin** [comment]
much of work on complete rewriting C code needed to make real array modifier work as node. For now non of custom node tree not binded to any object, as mentioned blend4web programmers.
