### ISSUE TITLE
Simple properties in nodes

### ISSUE THREAD

**Issue by ly29** [Sverchok/SverchokRedux#17]
Right now nodes are wonderfully simple. I would like to keep them that way, but at the same time I realize there are limits too how simple they can be. But as a general rule simplicity is a good starting point and then only adding complexity as needed.
## Properties

First up are properties. It is easy enough to imagine something along the lines of the following for simple properties, like integer, float, bool and string.

The current: 

``` python
import numpy as np

def linspace(start: float = 0.0, stop: float = 1.0, count: int = 10) -> [("linspace", np.ndarray)]:
    return np.linspace(start, stop, count)

linspace.label = "Linear space"
SvRxFunc = [linspace]
```

But if we look at the `np.linspace` documentation there are some additional parameters available, for now let us consider `endpoint: bool` which specifies if the generated linear space will be `[start, ... ,stop]` or `[start, ..., stop-step]`
Like this.

``` python
>>> np.linspace(0, 10, 5, endpoint=True)
array([  0. ,   2.5,   5. ,   7.5,  10. ])
>>> np.linspace(0, 10, 5, endpoint=False)
array([ 0.,  2.,  4.,  6.,  8.])
```

For me this seems like perfect candidate for an input that does not need to be a socket.

``` python
import numpy as np

def linspace(start: float = 0.0, stop: float = 1.0, count: int = 10,
             endpoint: (bool, "property") = True) -> [("linspace", np.ndarray)]:
    return np.linspace(start, stop, count, endpoint=endpoint)

linspace.label = "Linear space"
SvRxFunc = [linspace]
```

From this a property could automatically be generated, as well as a `draw_buttons` that automatically draws the properties.

Resulting in class corresponding the following:

``` python
class SvRxLinspaceNode(...

     svrx_properties = [("svrx_endpoint", "Endpoint")]
     svrx_endpoint = BoolProperty(update=update_svrx, name="Endpoint", default=True)

     def draw_buttons(self, context, layout):
         for name, text in svrx_properties:
             layout.prop(self, name, text=text)
```

In the compile stage these could then be put into a `kwargs` dict and passed along to the function along these lines.

``` python
>>> kwargs = {"endpoint": True}
>>> np.linspace(0, 10, 5, **kwargs)
array([  0. ,   2.5,   5. ,   7.5,  10. ])
```

This has the, positive, side effect that all properties must be placed after the socket inputs, as well a giving and order for the drawing of them.

Additional parameters for which things to only draw in the `draw_buttons_ext` as well as passing along a dict for the property creation/drawing could be supported.

For more complex case supplying a custom `draw_buttons` could be supported.

Also, perhaps far out, making something along these lines makes the properties easily inspectable, it is easy enough to imagine a properties socket being made available and creating an additional node, as needed, for drawing the parameters there.

``` python
class SvRxLinspacePropertiesNode(...
     svrx_properties = [("svrx_endpoint", "Endpoint")]
     svrx_endpoint = BoolProperty(update=update_svrx, name="Endpoint", default=True)

     def draw_buttons(self, context, layout):
         for name, text in svrx_properties:
             layout.prop(self, name, text=text)    
```

The sole purpose of this node being to be able to control multiple linspace nodes and vary the arguments of the properties as needed. For linspace this might not the most useful thing but for other cases it could very well offer an extreme additional flexibility while keeping a simple default case. The parameter dicts would the be treated and matched as other parts of the data tree.

**Comment by ly29** [comment]
The only real question here is the syntax, to make it sensible. For tomorrow.

**Comment by ly29** [comment]
So perhaps the sane way is just to declare the `bpy.props.FloatProperty` directly.

Like so:

``` python
import numpy as np
from bpy.props import BoolProperty


def linspace(start: float = 0.0, stop: float = 1.0, count: int = 10,
             endpoint: BoolProperty() = True) -> [("linspace", np.ndarray)]:
    return np.linspace(start, stop, count, endpoint=endpoint)
```

What happens here:

``` python
>>> linspace.__annotations__["endpoint"]
(<built-in function BoolProperty>, {})
```

It creates a tuple with function and a keyword dict to pass along to blender when the class becomes registered as a proper blender class. This dict can be modified to include the name and default parameters which when know from introspection/annotations removing the need to auto supply them.

Where the `name` `update` and `default` can be auto filled.

**Comment by ly29** [comment]
![skarmavbild 2015-12-09 kl 10 11 27](https://cloud.githubusercontent.com/assets/6241382/11681145/57c2bb74-9e5d-11e5-87b1-99629406b499.png)
Auto generated property in, now it just needs to get passed to the execution engine.

**Comment by ly29** [comment]
![skarmavbild 2015-12-09 kl 10 52 56](https://cloud.githubusercontent.com/assets/6241382/11682208/ac867474-9e63-11e5-9b21-badf90fc9108.png)

Working, also with multiple properties.

**Comment by ly29** [comment]
``` python
import numpy as np
from bpy.props import BoolProperty, FloatProperty


def linspace(start: float = 0.0, stop: float = 1.0, count: int = 10,
             endpoint: BoolProperty() = True,
             test: FloatProperty(description="test", subtype="ANGLE") = 2.0
             ) -> [("linspace", np.ndarray)]:
    return np.linspace(start, stop, count, endpoint=endpoint)

linspace.label = "Linear space"

SvRxFunc = [linspace]
```

**Comment by ly29** [comment]
@zeffii 
Is this sane?

**Comment by zeffii** [comment]
@ly29 I don't see why not. It's definitely still comprehensible.

I'm likely to declare nodes one param per line tho..I find it reads more pleasantly.

``` python
import numpy as np
from bpy.props import BoolProperty, FloatProperty


def linspace(
    start: float = 0.0,
    stop: float = 1.0,
    count: int = 10,
    endpoint: BoolProperty() = True,
    test: FloatProperty(description="test", subtype="ANGLE") = 2.0
    ) -> [("linspace", np.ndarray)]:

    return np.linspace(start, stop, count, endpoint=endpoint)

linspace.label = "Linear space"

SvRxFunc = [linspace]
```

**Comment by zeffii** [comment]
unless ofcourse the params fit on one line. (+/-100 chars)

**Comment by ly29** [comment]
My only concern is the undocumented behavior of the property functions, but if they change a change to something like the following would be simple enough.

``` python
def linspace(start: float = 0.0,
             stop: float = 1.0,
             count: int = 10,
             endpoint: (BoolProperty, {}) = True,
             test: (FloatProperty, {description: "test", subtype: "ANGLE"}) = 2.0
             ) -> [("linspace", np.ndarray)]:
    return np.linspace(start, stop, count, endpoint=endpoint)
```

**Comment by zeffii** [comment]
```
         endpoint: (BoolProperty, {}) = True,
         test: (FloatProperty, {description: "test", subtype: "ANGLE"}) = 2.0
```

how is that supposed to work, are you doing preprocessing? The tuple notation?

**Comment by ly29** [comment]
It that case the property would be created with `func(dict)` 
Right now this syntax works because `bpy.props.FloatProperty` etc. are returning `(func, kwargs)`

``` python
`>>> bpy.props.FloatProperty(name="test", default=10.0)
(<built-in function FloatProperty>, {'default': 10.0, 'name': 'test'})
```

Well, how it should work if things changes are problem for a later day. But there needs to be note about the expected behavior of the property functions.

**Comment by zeffii** [comment]
right - i follow now. I've seen that plenty of times in the REPL.

That part of the bpy api seems fairly cemented now, it's more likely that bpy gets new props than modifying existing ones to have a different signature.

**Comment by ly29** [comment]
This went much quicker than I expected and the syntax ended up being nicer. Now onwards.

**Comment by ly29** [comment]
Right now I store them in the node with a `svrx_` prefix to avoid name collisions with the standard node properties.

The dict taken from the annotation is updated with the `name` and `default` taken from the inspection, also an `update` method is supplied.

``` python
        prop = annotations[name]
        prop[1].update({"name": name,
                        "default": parameter.default,
                        "update": execute_tree})
        properties["svrx_{}".format(name)] = prop
```

**Comment by zeffii** [comment]
Some props will need a custom update method, so they can do some action after or before the execute_tree is called.

**Comment by ly29** [comment]
Yeah,  good point. That function would have to chain the default. Hmm

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/blob/master/nodes/basic_data/dupli_instances.py#L44-L53  for instance, because of the alternative `update=`
https://github.com/nortikin/sverchok/blob/master/nodes/basic_data/dupli_instances.py#L59-L61

**Comment by zeffii** [comment]
I realize the execution model is different, but it might still be necessary to have that option..

**Comment by ly29** [comment]
Yeah, also allowing get/set.

**Comment by ly29** [comment]
Of course right now changing any property results in a total recompilation of everything, I would like to move this to a model where at least values of properties are updated somewhat more clever.

**Comment by ly29** [comment]
Stopped the overriding, of user supplied data. Even though giving two different defaults should probably be considered an error I will leave that for now. 

``` python
        func, kwargs = annotations[name]
        defaults = {"name": name,
                    "default": parameter.default,
                    "update": execute_tree}
        for key, value in defaults.items():
            if key not in kwargs:
                kwargs[key] = value
```

**Comment by ly29** [comment]
if a property has `ext=True` it will be drawn in with `draw_buttons_ext`, instead of in the node.
With this I close this, the node based property control I leave for later.
