### ISSUE TITLE
gist_upload / download

### ISSUE THREAD

**Issue by zeffii** [Sverchok/SverchokRedux#25]
place: utils
function:  upload and download gists
useful in:   
- import/export tree json as gist
- import/export scripted node code (to gest, or to bpy.data.texts) - never autoexecuting.

intention is to have a set of generic library functions that can be imported wherever gist upload / download features are needed.  

proposed function signatures

``` python
def gist_upload(text_name, text_str):
    ...
    # no auth so we use anonymous gists for upload only, you can always fork manually 
    # to keep a record
    return acquired_gist_id
```

and

``` python
def gist_download(gist_id, location='TEXTS', path="/tmp/"):
    if location == 'TEXTS':
        download to bpy.data.texts[filename].from_string(downloaded_str)
    elif location == 'PATH':
        download to path

```

old versions of similar code:  
https://github.com/zeffii/rawr/tree/master/blender/scripts/addons_contrib/text_editor_gists

send multifile gist:  
https://github.com/zeffii/BlenderConsolePrompt/blob/master/addons_contrib/BCPrompt/bc_gist_utils.py

**Comment by zeffii** [comment]
maybe download can split out a list of filenames / bpy.data.texts that got different names because they existed already.. as a return variable..

**Comment by zeffii** [comment]
i use this or similar code 3 times, will turn into a function instead.
```
        if hasattr(json_to_parse, 'readall'):
            found_json = json_to_parse.readall().decode()
        else:
            found_json = json_to_parse.read().decode()
``` 

```python
def decode_url(parsable):
        if hasattr(json_to_parse, 'readall'):
            return parsable.readall().decode()
        else:
            return parsable.read().decode()
```

**Comment by ly29** [comment]
Is it possible to tag gists?

**Comment by zeffii** [comment]
sadly no, but one can give the gist a project name, which will return results in the gist search feature.. if the project name is 'some demo this' and you search 'demo'  then it will be suggested.

**Comment by ly29** [comment]
OK, I see, it would be nice to track public gists as idea exchange.

**Comment by zeffii** [comment]
we could build our own tagging / search feature. could even be hosted as a static webpage on github.

Collect a document (csv, json, whatever) 
name, gist_id, [description],(tag|tag|tag|tag) 

could be neat to have a database.

**Comment by ly29** [comment]
It would
