### ISSUE TITLE
.foreach_get/set performance review

### ISSUE THREAD

**Issue by ly29** [Sverchok/SverchokRedux#29]
Inspired by this blog post http://www.swineworld.org/2016/02/copying-vertices-to-numpy-arrays-in-blender.html I looked into .foreach performance.

We want a quick way to get blender data into a `np.array`, still I thought that it should be quicker than foreach with an numpy array, looking into blender the [blender source](https://git.blender.org/gitweb/gitweb.cgi/blender.git/blob/HEAD:/source/blender/python/intern/bpy_rna.c#l4527) I saw that a buffer object of the correct should give a big performance boost, since `.foreach_get` still uses the relevant python function to access the each index in the array, but it is a buffer protocol object of the right type it will use a point for direct access. Still I think there is some redirection etc going on deeper down perhaps but now we can get an impressive boost in getting data in and out of blender.

Knowing that blender uses C floats I tested with `dtype=np.float32` and now we get closer to the real data. 
For other mesh data types please consult [DNA_meshdata_types.h](https://git.blender.org/gitweb/gitweb.cgi/blender.git/blob/HEAD:/source/blender/makesdna/DNA_meshdata_types.h) 

Gist
https://gist.github.com/ly29/0edc351fd8e725431179

Notes
- np32 and np64 are the most important 
- array32 should perform better, it  does, is the init method that is really slow.
- np32 -> np64 converts data into float64 but is this needed? if the data isn't converted to float64,the data will be casted to float64 when we do for example `verts * np.array([1.1, 2, .1])` then instead of a import time...
- clearly it always makes sense to use numpy arrays go get the data quickly.

```
Cube with 98306 verts
np32 in 0.00901
np32 -> np64 in 0.01216
np64 in 0.14217
array32 in 0.54199
list foreach in 0.74891
list simpe in 0.78293

Cube.001 with 26 verts
np32 in 0.00007
np32 -> np64 in 0.00009
np64 in 0.00011
array32 in 0.00023
list foreach in 0.00021
list simpe in 0.00020
```

**Comment by ly29** [comment]
With the array.array init moved into setup it is on par with np32

```
Cube with 98306 verts
np32 in 0.00881
np32 -> np64 in 0.01153
np64 in 0.14255
array32 in 0.00902
```

**Comment by ly29** [comment]
So thanks to Campbell foresight we have a very quick way of getting data, otherwise I was thinking about hacking a bit of C.

**Comment by ly29** [comment]
Note that this is more than **100X** the speed of Sverchok doing the old way.

**Comment by zeffii** [comment]
That's exciting to say the least. np32 looks like it will be the performance barrier. Worth writing some of our heavier non bmesh/bpy routines in a lower level language that outputs np32 arrays. (if it can't be expressed in a fast numpy construct)
