### ISSUE TITLE
Introspection for all nodes from day 1

### ISSUE THREAD

**Issue by zeffii** [Sverchok/SverchokRedux#5]
I think this has been mentioned, but i'd like to develop the idea to be positive it is a first class piece of the new puzzle.

Part of the problem with serializing the node tree to json was due to inconsistencies in how we described nodes, but also down to a slightly 'sparse' pyNodes api. Prior to writing the .json I/O we didn't know or worry about being able to query all params easily, and didn't need to enforce strict param conventions. We realized that the pyNodes API does not by default give a handy representation of the Node or the Tree. (if it does... we didn't find it)

This means the .json IO was/is a bit convoluted and more verbose than the concept requires, it can be simpler and I think we know how to approach it now.

Because some nodes have multiple states and dynamic sockets, we should be able to easily ask the node its _state_ and sockets and get a descriptor back (json?). We should also be able to set the entire state (sockets, values, enums...location..whatever) from the same json.

This would shift the clumsy code out of the IO and make it part of the node superclass.

**Comment by ly29** [comment]
This is an extremely important point.

Furthermore, the node definition should be able to know which sockets it should have so additional socket can be added to nodes in the correct place when a node gets a new socket, so adding a new socket is also an automatic process.

I think a dict like format that is easier to use directly in python but serializes easily to json is a better choice.

Furthermore we should split this into two parts, `get_ui_state` and `get_svrx_state` (not suggesting those function names) so the we get what we want exactly.

**Comment by zeffii** [comment]
yeah, dict / json serialization is trivial. dict is fine for the node specific IO..

**Comment by ly29** [comment]
The flow of info goes something like this.

```
node definition -> dict -> blender node ui
blender node ui -> dict -> json
blender node ui -> dict -> execution unit 
file or other source -> json -> dict -> blender node ui
```

a nice side effect is that we don't have to maintain node groups as hidden node groups but can keep them in other formats.

**Comment by zeffii** [comment]
My original reason for implementing .json IO was never with a secondary use (nodegroups) in the back of the mind, but it completely makes sense that it was used this way. 

Yes, on the whole this should allow for quite nice abstractions in multiple places. To the point where it could be conceivable that we draw our own node view in C++ / openframeworks..

![image](https://cloud.githubusercontent.com/assets/619340/8302581/c4429012-1997-11e5-9b10-caa516ae5d40.png)

**Comment by nortikin** [comment]
Furthermore we should split this into two parts, `get_ui_state` and `get_svrx_state`

@ly29 
What do you mean by svrx state?

**Comment by nortikin** [comment]
@zeffii  our own ui? we binded tight to blender anyway, do you mean http yavascript UI?

**Comment by zeffii** [comment]
I meant a dedicated cross platform custom Nodeview written in C++ using openframeworks. I realize this is not the goal of Redux, but if we manage to succesfuly divorce UI from processing steps, then.. in the end.. the core code won't care what is used to generate the node tree.. -- But it is not essential yet.

**Comment by ly29** [comment]
@nortikin 
svrx = SVerchokREdux, in this case I mean the part of the ui that is important for the execution, in other words the parameters that decide the behavior of the execution unit. the relevant blender properties.

**Comment by nortikin** [comment]
http://drichard.org/mindmaps open file i sent to you email with this online service and edit if you want
@ly29 @zeffii

**Comment by nortikin** [comment]
or propose algorythm mindmap that fits more to issue

**Comment by nortikin** [comment]
there is no joints between elements, so maybe www.mindomo.com/
think last fits us

**Comment by ly29** [comment]
I have to admit to not using digital tools for these kind of things, mostly do it by hand. Anyway some documentation of how it all fits together is needed.

**Comment by zeffii** [comment]
regarding mindmapping, I don't want to sign up to those sites.. But mindmapping is worth trying anyway.
![image](https://cloud.githubusercontent.com/assets/619340/8324299/6f6b6dbc-1a4f-11e5-98d9-bc3946493cd2.png)

**Comment by zeffii** [comment]
Additional reasons for Introspection, the SvStethoscope, or print debugger all need to be able to acquire node data and be able to show selections of it (another good reason to have something like np_Mesh with the ability to describe a mesh in a flat or partially nested way)

**Comment by nortikin** [comment]
https://en.wikipedia.org/wiki/Directed_acyclic_graph
WWW implementation?
just to have front eye what we do mindmap helps a lot.

**Comment by ly29** [comment]
![data_flow](https://cloud.githubusercontent.com/assets/6241382/8324021/224ea5e2-1a4c-11e5-9b5b-37a4cd0e44af.png)

Something like this. Really ugly.

**Comment by nortikin** [comment]
definitions to manipulate data - if we have vertices and digits to do some math, in numpy it should be as `vx,vy,vz,vx,vy,vz,...` and `a,a,a,b,b,b,...` that means numpy to populate digits. or if we talk about formula node it should have ability to maipulate as vertex+vertex and vertex+digit and work in different ways, completely rewritint list tools and formula and math tools. it is huuuge aMount of job... i need payed vocation to handle this...
But if we will do it will be perfect.
some nodes hard coded earlyer, example zip node, we donno how it do, Alex says `don't ask me how i writed it`. Zip with different levels - is it possible in numpy?

**Comment by zeffii** [comment]
A lot of the functionality which is complicated using straight-python, is made a lot easier and faster using numpy. especially things like reversing/adding/slicing/shifting.. Some things might be harder, but now you'll have more people looking at the code, not just Alex :)

**Comment by nortikin** [comment]
reversing/adding/slicing/shifting not so difficult, levels is limitation.
for example shifting np.arrey([[[1,2,3],[4,5,6]],[[7,8,9],[0,0,0]]]) have to become
3lvl [[[3,1,2],[6,4,5]],[[9,7,8],[0,0,0]]]
2lvl [[[4,5,6],[1,2,3]],[[0,0,0],[7,8,9]]]
1lvl [[[7,8,9],[0,0,0]],[[1,2,3],[4,5,6]]]
so slice np.arreys (there are two+) will be changed or will be changed flat arrey digits order?

if flat arrey than how in simple way?

**Comment by nortikin** [comment]
can be with roll, than maybe we should define vertices as 2d arrey to choose axis simply?
not everything will be flat arrey... than we have two classes of data?

**Comment by zeffii** [comment]
The levels of nested-ness must worked away first, that's what the lookup tables would be for. If we are to use numpy features which are fast, then we have no choice. (Any manual translations would result in code which is no faster than what we have now...)

with np.array we get the ability to keep the original data unchanged and simply pass around different representations ("views").

**Comment by nortikin** [comment]
so flat data not schanged ever? only lookups? o_O

**Comment by ly29** [comment]
Zip and list operation will be somewhat comeplicated to write, on the other hand I think they will become needed less.
As long we can define operations well we can work out how to do them.

**Comment by ly29** [comment]
Even if one is slow at first, it can be optimized later.

**Comment by nortikin** [comment]
No less needed, list operations is one of cornerstones. Most of work i do with them.
<sub>I will try to solve </sub>

**Comment by zeffii** [comment]
yes nortikin, to use numpy at its <sup>FORTRAN</sup> speeds we must have less esoteric data, but lookups are the way to deal with that (hence also the lookup table for bmesh.. `verts.ensure_lookup_table`)

**Comment by ly29** [comment]
@nortikin 
I honestly think they will be less needed when many of the things we are planning are done.

However they are absolutely very important. They will not go away.

**Comment by zeffii** [comment]
It is a Redux after all. In the end we want 'feature parity', no regressions. This is an opportunity to design the data types and structures differently too. We get the `FORTRAN` speeds only by revisiting our notions of how data is 
- stored
- passed around
- copied (if needed)
- operated on

**Comment by zeffii** [comment]
I think this discussion deserves it own thread, because it is starting to go into detail about something else. (of course equally important...)

**Comment by ly29** [comment]
Yeah the data structure and how we can parse it deserves its own thread. As well as the mind maps

**Comment by ly29** [comment]
Back on topic. Serialzing node layout, looking at the code in io panel for Sverchok it feels a bit to complex, but will use it as a starting point. https://github.com/nortikin/sverchok/blob/master/utils/sv_IO_panel_tools.py

**Comment by ly29** [comment]
A lot of code is dealing with corner cases of specific nodes, if we avoid that, at least while starting up, it can be a lot simpler. Hmm.

**Comment by zeffii** [comment]
the nodes should describe themselves better. so the IO only needs to call a function on each node and get everything it needs for serialization. ( and in return, a " state_pusher" / setter )

**Comment by ly29** [comment]
yeah,`node -> data` is the most important right now. the same with sockets.
it is an interesting difference between designing it and bolting it on afterwards.

**Comment by zeffii** [comment]
yes. that was a painful bit of code to write, but necessary for progress. It showed how convoluted the code needed to be to serialize the tree in it's current state, and I think pointed to the areas where more abstraction would improve the tree's parse-ability. The pynodes API comes with nothing out of the box.

**Comment by ly29** [comment]
Right now I have made it extremely simple for myself, no nodes have any custom properties, all data is in the sockets. Of course this is an impossible oversimplification to have usable system but I think I will start it like this and slowly add more things.

**Comment by zeffii** [comment]
enum was the most painful `bpy.props` type to parse.

**Comment by ly29** [comment]
created a mechanism for it but putting it in the node base class, and also serialize the sockets.
if node needs special consideration is has to implement its own `serialize(self)` and same with sockets. The big advantage is the the exceptions happen where they make sense in context and not in the main code.

```
>>> D.node_groups['NodeTree'].nodes['Linear space'].serialize()
{'color': (0.6079999804496765, 0.6079999804496765, 0.6079999804496765), 'bl_idname': 'SvRxNodelinspace', 'inputs': [{'name': 'start', 'default_value': 0.0, 'bl_idname': 'SvRxFloatSocket'}, {'name': 'stop', 'default_value': 1.0, 'bl_idname': 'SvRxFloatSocket'}, {'name': 'count', 'default_value': 10, 'bl_idname': 'SvRxIntSocket'}], 'height': 100.0, 'hide': False, 'width': 140.0, 'location': (-217.97604370117188, -30.128952026367188), 'label': '', 'params': {}, 'outputs': [{'name': 'linspace', 'default_value': 0.0, 'bl_idname': 'SvRxFloatSocket'}]}
```

**Comment by ly29** [comment]
Now just implent the same for the tree. Then get to the next step of transform these dicts to something useful.

**Comment by ly29** [comment]
Working I/O, some things I know are broken but now the responsibility falls on the nodes when creating tricky things. 
Important gotcha, dynamic sockets is todo.
Also socket loading.
![skarmavbild 2015-11-17 kl 20 49 04](https://cloud.githubusercontent.com/assets/6241382/11222765/b3757c9c-8d6c-11e5-9b4e-c21db89c0b80.png)

**Comment by ly29** [comment]
Socket values load now.
All the code is kept simple for now. I am sure some more cases will be needed to be taken care of.
I think this resolves this issue.
Onwards to make thing actually happen.

**Comment by ly29** [comment]
I will close this issue because it feels good. I'm sure there will be reasons to revisit this topic but for now I consider it solved.

**Comment by nortikin** [comment]
i have changed order of reading json, it starts from creating text file for scripted node, than load it, but i cannot load somehow. What it should be? More over, after switch loading order is fails with profile node... i made wrong

**Comment by ly29** [comment]
@nortikin please create an issue over on the Sverchok issue tracker.

**Comment by nortikin** [comment]
@ly29 sorry.

**Comment by ly29** [comment]
As I expected, I did not consider something important.

``` python
node.serialize()
```

Of course only works for SvRx nodes, for other important nodes like frames and reroutes we need to handle the code a bit differently.  Of course keeping the `node.serialize()` interface (perhaps with a different name like `dump`) seems like good idea.
The structure needs to be changed bit...

**Comment by ly29** [comment]
`serialize` works now, but load does not load reroutes etc.

**Comment by nortikin** [comment]
File "/home/ololo/.config/blender/2.76/scripts/addons/SverchokRedux/core/compiler.py", line 1, in <module>
    from .execute import GraphNode
  File "/home/ololo/.config/blender/2.76/scripts/addons/SverchokRedux/core/execute.py", line 3, in <module>
    from .compiler import create_graph
ImportError: cannot import name 'create_graph'
WTF?
is it ok?

**Comment by nortikin** [comment]
how you test it? where to put parts?
